export const languages = ['en','nl','de','fr','es','zh','ru'] as const;
export type Lang = typeof languages[number];
export const t: Record<Lang, Record<string,string>> = {
 en:{hero:'Luxury snacks from the Netherlands to the world',subtitle:'Discover Dutch favourites and international cult snacks in one elegant mobile-first shop.',shop:'Shop now',cart:'Basket',wishlist:'Wishlist',reviews:'Reviews',login:'Log in',logout:'Log out',checkout:'Checkout',search:'Search snacks',admin:'Admin',recovery:'Saved basket restored for your account.'},
 nl:{hero:'Luxe snacks vanuit Nederland naar de wereld',subtitle:'Ontdek Nederlandse favorieten en internationale snacks in één stijlvolle shop.',shop:'Shop nu',cart:'Winkelmand',wishlist:'Verlanglijst',reviews:'Reviews',login:'Inloggen',logout:'Uitloggen',checkout:'Afrekenen',search:'Zoek snacks',admin:'Beheer',recovery:'Opgeslagen winkelmand hersteld.'},
 de:{hero:'Luxus-Snacks aus den Niederlanden in die Welt',subtitle:'Niederländische Klassiker und internationale Kult-Snacks in einem eleganten Shop.',shop:'Jetzt shoppen',cart:'Warenkorb',wishlist:'Wunschliste',reviews:'Bewertungen',login:'Einloggen',logout:'Ausloggen',checkout:'Zur Kasse',search:'Snacks suchen',admin:'Admin',recovery:'Gespeicherter Warenkorb wiederhergestellt.'},
 fr:{hero:'Snacks de luxe des Pays-Bas vers le monde',subtitle:'Favoris néerlandais et snacks internationaux dans une boutique élégante.',shop:'Acheter',cart:'Panier',wishlist:'Favoris',reviews:'Avis',login:'Connexion',logout:'Déconnexion',checkout:'Commander',search:'Rechercher',admin:'Admin',recovery:'Panier sauvegardé restauré.'},
 es:{hero:'Snacks de lujo desde Países Bajos al mundo',subtitle:'Favoritos neerlandeses y snacks internacionales en una tienda elegante.',shop:'Comprar',cart:'Cesta',wishlist:'Favoritos',reviews:'Reseñas',login:'Entrar',logout:'Salir',checkout:'Pagar',search:'Buscar snacks',admin:'Admin',recovery:'Cesta guardada restaurada.'},
 zh:{hero:'来自荷兰的奢华零食，送往全球',subtitle:'在一个优雅商店中探索荷兰经典与国际人气零食。',shop:'立即购买',cart:'购物篮',wishlist:'愿望清单',reviews:'评价',login:'登录',logout:'退出',checkout:'结账',search:'搜索零食',admin:'管理',recovery:'已恢复保存的购物篮。'},
 ru:{hero:'Премиальные снеки из Нидерландов по всему миру',subtitle:'Голландская классика и международные хиты в элегантном магазине.',shop:'Купить',cart:'Корзина',wishlist:'Избранное',reviews:'Отзывы',login:'Войти',logout:'Выйти',checkout:'Оплатить',search:'Поиск снеков',admin:'Админ',recovery:'Сохраненная корзина восстановлена.'}
};
