export type Product = { id: string; name: string; region: string; category: string; priceEur: number; description: string; tags: string[]; image: string; stock: number };
export const products: Product[] = [
{id:'stroopwafels',name:'Dutch Stroopwafels',region:'Netherlands',category:'Sweet',priceEur:3.49,description:'Caramel syrup waffles, perfect over coffee.',tags:['dutch','classic'],image:'🍯',stock:120},
{id:'drop-mix',name:'Dutch Drop Mix',region:'Netherlands',category:'Candy',priceEur:2.99,description:'Sweet and salty licorice selection.',tags:['licorice'],image:'🖤',stock:80},
{id:'borrelnootjes',name:'Borrelnootjes Paprika',region:'Netherlands',category:'Savory',priceEur:2.79,description:'Crunchy coated peanuts with paprika seasoning.',tags:['nuts'],image:'🥜',stock:100},
{id:'kaas-crackers',name:'Gouda Cheese Crackers',region:'Netherlands',category:'Savory',priceEur:2.69,description:'Crispy crackers with a rich cheese taste.',tags:['cheese'],image:'🧀',stock:90},
{id:'hagelslag-bites',name:'Hagelslag Chocolate Bites',region:'Netherlands',category:'Chocolate',priceEur:3.29,description:'Milk chocolate sprinkle-style snack bites.',tags:['chocolate'],image:'🍫',stock:65},
{id:'pocky-chocolate',name:'Pocky Chocolate',region:'Japan',category:'Sweet',priceEur:2.49,description:'Biscuit sticks dipped in chocolate cream.',tags:['japan'],image:'🥢',stock:75},
{id:'pocky-strawberry',name:'Pocky Strawberry',region:'Japan',category:'Sweet',priceEur:2.59,description:'Crisp biscuit sticks with strawberry coating.',tags:['japan','fruit'],image:'🍓',stock:70},
{id:'kitkat-matcha',name:'KitKat Matcha',region:'Japan',category:'Chocolate',priceEur:4.99,description:'Mini wafers with green tea chocolate.',tags:['matcha'],image:'🍵',stock:45},
{id:'ramune-candy',name:'Ramune Soda Candy',region:'Japan',category:'Candy',priceEur:2.39,description:'Fizzy soda-flavored tablets.',tags:['fizzy'],image:'🫧',stock:88},
{id:'mochi-redbean',name:'Red Bean Mochi',region:'Japan',category:'Sweet',priceEur:3.99,description:'Soft rice cakes with red bean filling.',tags:['mochi'],image:'🍡',stock:40},
{id:'shrimp-chips',name:'Shrimp Chips',region:'Korea',category:'Savory',priceEur:2.89,description:'Light crunchy chips with seafood flavor.',tags:['chips'],image:'🦐',stock:60},
{id:'honey-butter-chips',name:'Honey Butter Chips',region:'Korea',category:'Savory',priceEur:3.49,description:'Sweet-savory potato chips with honey butter.',tags:['chips'],image:'🍯',stock:55},
{id:'choco-pie',name:'Choco Pie',region:'Korea',category:'Chocolate',priceEur:4.49,description:'Soft cake pies with marshmallow and chocolate.',tags:['cake'],image:'🥧',stock:52},
{id:'tteokbokki-snack',name:'Tteokbokki Crunch Snack',region:'Korea',category:'Savory',priceEur:3.29,description:'Crunchy spicy-sweet rice cake snack.',tags:['spicy'],image:'🌶️',stock:58},
{id:'seaweed-crisps',name:'Roasted Seaweed Crisps',region:'Korea',category:'Savory',priceEur:1.99,description:'Thin roasted seaweed sheets with salt.',tags:['vegan'],image:'🌿',stock:95},
{id:'takis-fuego',name:'Takis Fuego',region:'Mexico',category:'Savory',priceEur:4.49,description:'Rolled tortilla chips with chili-lime heat.',tags:['spicy'],image:'🔥',stock:66},
{id:'pulparindo',name:'Pulparindo Tamarind',region:'Mexico',category:'Candy',priceEur:1.79,description:'Tamarind candy with sweet, sour, salty heat.',tags:['tamarind'],image:'🌶️',stock:85},
{id:'mazapan',name:'Mazapan Peanut Candy',region:'Mexico',category:'Sweet',priceEur:1.49,description:'Crumbly sweet peanut confection.',tags:['peanut'],image:'🥜',stock:110},
{id:'duvalin',name:'Duvalin Vanilla Strawberry',region:'Mexico',category:'Sweet',priceEur:1.29,description:'Creamy two-flavor candy cup.',tags:['cream'],image:'🍓',stock:100},
{id:'chamoy-gummies',name:'Chamoy Gummies',region:'Mexico',category:'Candy',priceEur:3.69,description:'Fruit gummies coated with chamoy seasoning.',tags:['spicy','gummy'],image:'🍬',stock:57},
{id:'reeses-cups',name:'Reese’s Peanut Butter Cups',region:'USA',category:'Chocolate',priceEur:2.19,description:'Chocolate cups with peanut butter filling.',tags:['peanut'],image:'🥜',stock:99},
{id:'hersheys-cookies',name:'Hershey’s Cookies n Creme',region:'USA',category:'Chocolate',priceEur:2.49,description:'White creme bar with cookie pieces.',tags:['cookies'],image:'🍪',stock:73},
{id:'cheetos-crunchy',name:'Cheetos Crunchy',region:'USA',category:'Savory',priceEur:3.99,description:'Crunchy cheese-flavored corn snacks.',tags:['cheese'],image:'🧀',stock:72},
{id:'sour-patch',name:'Sour Patch Kids',region:'USA',category:'Candy',priceEur:2.99,description:'Sour-then-sweet gummy candy.',tags:['sour'],image:'🍬',stock:84},
{id:'pop-tarts',name:'Pop-Tarts Frosted Strawberry',region:'USA',category:'Sweet',priceEur:4.99,description:'Toaster pastries with strawberry filling.',tags:['breakfast'],image:'🥐',stock:43},
{id:'walkers-shortbread',name:'Scottish Shortbread',region:'UK',category:'Sweet',priceEur:3.79,description:'Buttery shortbread biscuits.',tags:['butter'],image:'🍪',stock:61},
{id:'monster-munch',name:'Monster Munch Pickled Onion',region:'UK',category:'Savory',priceEur:2.99,description:'Pickled onion flavored corn snacks.',tags:['chips'],image:'🧅',stock:54},
{id:'jammie-dodgers',name:'Jammie Dodgers',region:'UK',category:'Sweet',priceEur:3.29,description:'Jam-filled shortcake biscuits.',tags:['jam'],image:'🍓',stock:69},
{id:'maltesers',name:'Maltesers',region:'UK',category:'Chocolate',priceEur:2.89,description:'Malted milk balls covered in chocolate.',tags:['malted'],image:'🍫',stock:82},
{id:'wine-gums',name:'Wine Gums',region:'UK',category:'Candy',priceEur:2.59,description:'Classic chewy fruit gums.',tags:['gummy'],image:'🍬',stock:91},
{id:'haribo-goldbears',name:'Haribo Goldbears',region:'Germany',category:'Candy',priceEur:2.49,description:'Classic gummy bears in fruit flavors.',tags:['gummy'],image:'🐻',stock:120},
{id:'ritter-sport',name:'Ritter Sport Alpine Milk',region:'Germany',category:'Chocolate',priceEur:2.79,description:'Square milk chocolate bar.',tags:['chocolate'],image:'🍫',stock:76},
{id:'leibniz',name:'Leibniz Butter Biscuits',region:'Germany',category:'Sweet',priceEur:2.99,description:'Crisp butter biscuits.',tags:['biscuit'],image:'🍪',stock:86},
{id:'paprika-chips',name:'German Paprika Chips',region:'Germany',category:'Savory',priceEur:2.89,description:'Potato chips with paprika seasoning.',tags:['chips'],image:'🥔',stock:77},
{id:'hanuta',name:'Hanuta Hazelnut Wafer',region:'Germany',category:'Chocolate',priceEur:3.59,description:'Hazelnut cream between crispy wafers.',tags:['hazelnut'],image:'🌰',stock:48},
{id:'lu-petit-ecolier',name:'Petit Écolier Chocolate Biscuits',region:'France',category:'Chocolate',priceEur:3.49,description:'Biscuits topped with chocolate tablets.',tags:['biscuit'],image:'🍫',stock:68},
{id:'madeleines',name:'French Madeleines',region:'France',category:'Sweet',priceEur:3.99,description:'Soft shell-shaped sponge cakes.',tags:['cake'],image:'🧁',stock:46},
{id:'brets-chips',name:'Brets Cheese Chips',region:'France',category:'Savory',priceEur:3.49,description:'French potato chips with cheese flavor.',tags:['chips'],image:'🧀',stock:50},
{id:'carambar',name:'Carambar Caramel',region:'France',category:'Candy',priceEur:2.29,description:'Chewy caramel sticks.',tags:['caramel'],image:'🍯',stock:88},
{id:'calissons',name:'Calissons',region:'France',category:'Sweet',priceEur:5.99,description:'Almond and candied fruit sweets.',tags:['almond'],image:'💎',stock:28},
{id:'pan-di-stelle',name:'Pan di Stelle Cookies',region:'Italy',category:'Sweet',priceEur:3.79,description:'Chocolate hazelnut star cookies.',tags:['cookies'],image:'⭐',stock:49},
{id:'taralli',name:'Italian Taralli',region:'Italy',category:'Savory',priceEur:3.19,description:'Crunchy ring-shaped olive oil crackers.',tags:['crackers'],image:'🥨',stock:72},
{id:'baci',name:'Baci Hazelnut Chocolates',region:'Italy',category:'Chocolate',priceEur:5.49,description:'Hazelnut chocolates with gianduja filling.',tags:['hazelnut'],image:'🌰',stock:38},
{id:'amaretti',name:'Amaretti Cookies',region:'Italy',category:'Sweet',priceEur:3.59,description:'Crisp almond cookies.',tags:['almond'],image:'🍪',stock:58},
{id:'san-carlo-chips',name:'San Carlo Tomato Chips',region:'Italy',category:'Savory',priceEur:2.99,description:'Italian chips with tomato seasoning.',tags:['chips'],image:'🍅',stock:62},
{id:'white-rabbit',name:'White Rabbit Candy',region:'China',category:'Candy',priceEur:2.99,description:'Creamy milk candy wrapped in rice paper.',tags:['milk'],image:'🐇',stock:71},
{id:'haw-flakes',name:'Haw Flakes',region:'China',category:'Sweet',priceEur:1.99,description:'Tangy hawthorn fruit discs.',tags:['fruit'],image:'🔴',stock:92},
{id:'prawn-crackers',name:'Chinese Prawn Crackers',region:'China',category:'Savory',priceEur:2.49,description:'Light crispy prawn-flavored crackers.',tags:['seafood'],image:'🦐',stock:85},
{id:'lychee-jelly',name:'Lychee Jelly Cups',region:'China',category:'Sweet',priceEur:3.99,description:'Mini lychee-flavored jelly cups.',tags:['fruit'],image:'🍈',stock:64},
{id:'sesame-snaps',name:'Sesame Snaps',region:'Global',category:'Sweet',priceEur:1.89,description:'Crispy sesame seed brittle.',tags:['sesame'],image:'🌾',stock:78}
];
export const categories = Array.from(new Set(products.map(p=>p.category)));
export const regions = Array.from(new Set(products.map(p=>p.region)));
